services:
  foodcnn:
    build:
      context: ./FoodCNN

  pretrazivko:
    build:
      context: ./pretrazivko

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./devops/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - foodcnn
      - pretrazivko
